"""Deterministic composers used when no LLM is available.

These are *template engines*, not fake model output: they reorganise the user's
own brief (sentences, headings, bullets) into a professional structure and label
the result with ``synthesis: "deterministic"`` plus an explicit note. No facts,
numbers, sources or quotes are invented.
"""

from __future__ import annotations

import re
from typing import Any

STOPWORDS = {
    "the", "a", "an", "and", "or", "but", "for", "with", "about", "into", "from", "that", "this", "these", "those",
    "please", "write", "create", "make", "generate", "build", "produce", "give", "me", "my", "our", "your", "report",
    "document", "doc", "deck", "slide", "slides", "presentation", "site", "website", "page", "using", "use",
}


def extract_points(brief: str, limit: int = 40) -> list[str]:
    """Split a brief into meaningful lines/sentences (the user's own words)."""
    if not brief:
        return []
    lines: list[str] = []
    for raw in re.split(r"\r?\n", brief):
        item = raw.strip()
        item = re.sub(r"^[-*•\d.)\s]+", "", item).strip()
        if not item:
            continue
        lines.append(item)

    if len(lines) <= 1:
        # Single block of prose → split into sentences.
        text = lines[0] if lines else brief
        lines = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if s.strip()]

    out: list[str] = []
    for item in lines:
        item = re.sub(r"\s+", " ", item).strip("# ").strip()
        if len(item) < 3:
            continue
        out.append(item)
        if len(out) >= limit:
            break
    return out


def keywords(text: str, limit: int = 8) -> list[str]:
    words = re.findall(r"[A-Za-z][A-Za-z\-]{3,}", (text or "").lower())
    seen: list[str] = []
    for w in words:
        if w in STOPWORDS or w in seen:
            continue
        seen.append(w)
        if len(seen) >= limit:
            break
    return seen


def draft_sections(title: str, brief: str) -> list[dict[str, Any]]:
    """Compose a structured document outline from the brief (no invented facts)."""
    points = extract_points(brief, limit=24)
    heading_lines = [p for p in points if _looks_like_heading(p)]
    body_points = [p for p in points if p not in heading_lines]

    sections: list[dict[str, Any]] = []

    overview_body = (
        f"This document addresses: {title}. "
        + (" ".join(body_points[:2]) if body_points else "The brief supplied did not include additional detail.")
    )
    sections.append({"heading": "Overview", "body": overview_body, "bullets": points[:3]})

    if body_points:
        sections.append(
            {
                "heading": "Key Points",
                "body": "The following points were extracted directly from the request.",
                "bullets": body_points[:8],
            }
        )

    for heading in heading_lines[:8]:
        sections.append(
            {
                "heading": heading[:80],
                "body": f"Section derived from the brief line: “{heading}”.",
                "bullets": [],
            }
        )

    sections.append(
        {
            "heading": "Approach",
            "body": "Work was structured into requirements, analysis, production and validation phases, "
            "each with an explicit artifact.",
            "bullets": ["Clarify scope", "Produce artifacts", "Validate outputs", "Report limitations"],
        }
    )
    sections.append(
        {
            "heading": "Limitations",
            "body": "This document was composed deterministically from the supplied brief because no language "
            "model was available in this environment. Content is limited to the request's own wording; "
            "no external facts, figures or sources were introduced.",
            "bullets": [],
        }
    )
    sections.append(
        {
            "heading": "Next Steps",
            "body": "Connect a model provider (OPENAI_BASE_URL / OPENAI_API_KEY) to enable narrative "
            "synthesis, or supply a section outline directly.",
            "bullets": [],
        }
    )
    return sections


def draft_slides(title: str, brief: str, target: int = 10) -> list[dict[str, Any]]:
    target = max(8, min(12, target))
    points = extract_points(brief, limit=24)
    keys = keywords(brief)

    slides: list[dict[str, Any]] = []
    slides.append(
        {
            "title": title,
            "bullets": [p for p in points[:2]] or ["Generated by LocalAI Workspace"],
            "notes": "Opening slide. Composition is deterministic: no language model was available.",
        }
    )
    slides.append(
        {
            "title": "Agenda",
            "bullets": ["Context", "Key points", "Approach", "Limitations", "Next steps"],
            "notes": "Orient the audience.",
        }
    )

    chunk = max(1, len(points) // max(1, target - 4)) if points else 1
    i = 0
    section_no = 1
    while i < len(points) and len(slides) < target - 2:
        group = points[i : i + min(4, chunk + 1)]
        slides.append(
            {
                "title": f"Key Points {section_no}",
                "bullets": group,
                "notes": f"Derived from the brief (section {section_no}).",
            }
        )
        i += max(2, chunk)
        section_no += 1

    while len(slides) < target - 2:
        if keys:
            key = keys[(len(slides) - 2) % len(keys)]
            slides.append({"title": f"Focus: {key.title()}", "bullets": [f"Considerations related to {key}"], "notes": ""})
        else:
            slides.append({"title": f"Discussion {len(slides) - 1}", "bullets": ["Add supporting detail"], "notes": ""})

    slides.append(
        {
            "title": "Limitations",
            "bullets": ["Deck composed without an LLM", "Content limited to the supplied brief"],
            "notes": "State limitations explicitly.",
        }
    )
    slides.append(
        {
            "title": "Next Steps",
            "bullets": ["Provide a section outline for richer content", "Connect a model provider for narrative synthesis"],
            "notes": "Closing slide.",
        }
    )
    return slides[:target]


def build_static_site(site_name: str, brief: str, style: str = "") -> dict[str, str]:
    """Compose a real, responsive, accessible static site from the brief."""
    points = extract_points(brief, limit=12)
    headline = (points[0] if points else site_name).strip()
    description = " ".join(points[1:4]) if len(points) > 1 else "A static site generated by LocalAI Workspace."
    features = points[1:7] or [
        "Responsive layout",
        "Accessible markup",
        "No build step required",
        "Deterministically composed",
    ]
    features = features[:6]

    feature_cards = "\n".join(
        f'      <article class="card">\n        <h3>{_esc(_shorten(f, 60))}</h3>\n        <p>{_esc(f)}</p>\n      </article>'
        for f in features
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{_esc(site_name)}</title>
  <meta name="description" content="{_esc(_shorten(description, 150))}">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header>
    <h1>{_esc(site_name)}</h1>
    <nav aria-label="Primary">
      <a href="#features">Features</a>
      <a href="#about">About</a>
      <a href="#contact">Contact</a>
    </nav>
  </header>

  <main>
    <section id="hero" aria-labelledby="hero-title">
      <h2 id="hero-title">{_esc(headline)}</h2>
      <p>{_esc(description)}</p>
    </section>

    <section id="features" aria-labelledby="features-title">
      <h2 id="features-title">Features</h2>
      <div class="grid">
{feature_cards}
      </div>
    </section>

    <section id="about" aria-labelledby="about-title">
      <h2 id="about-title">About</h2>
      <p>This site was composed deterministically from the supplied brief
      ({_esc(", ".join(keywords(brief, 6)) or "no keywords extracted")}).</p>
    </section>

    <section id="contact" aria-labelledby="contact-title">
      <h2 id="contact-title">Contact</h2>
      <form action="#" method="post">
        <label for="name">Name</label>
        <input id="name" name="name" type="text" required>
        <label for="email">Email</label>
        <input id="email" name="email" type="email" required>
        <label for="message">Message</label>
        <textarea id="message" name="message" rows="4" required></textarea>
        <button type="submit">Send</button>
      </form>
    </section>
  </main>

  <footer>
    <p>Built by LocalAI Workspace{(" · " + _esc(style)) if style else ""}</p>
  </footer>
  <script src="script.js"></script>
</body>
</html>
"""
    return {"index.html": html, "styles.css": _CSS, "script.js": _JS}


_CSS = """:root{--bg:#0b1220;--surface:#111a2e;--fg:#e6edf7;--muted:#9aa8bd;--accent:#4f9cf9;--radius:14px}
*{box-sizing:border-box}
html{scroll-behavior:smooth}
body{margin:0;font-family:system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;background:var(--bg);color:var(--fg);line-height:1.65}
header,main,footer{max-width:1080px;margin:0 auto;padding:1.5rem}
header{display:flex;flex-wrap:wrap;gap:1rem;align-items:center;justify-content:space-between;border-bottom:1px solid #1e293b}
h1,h2,h3{line-height:1.25}
nav a{color:var(--accent);margin-right:1rem;text-decoration:none}
nav a:hover,nav a:focus{text-decoration:underline}
a:focus-visible,button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid var(--accent);outline-offset:2px}
section{margin:2rem 0}
.grid{display:grid;gap:1.25rem;grid-template-columns:repeat(auto-fit,minmax(240px,1fr))}
.card{background:var(--surface);border:1px solid #223052;border-radius:var(--radius);padding:1.25rem}
form{display:grid;gap:.5rem;max-width:520px}
label{font-size:.95rem;color:var(--muted)}
input,textarea{padding:.65rem .75rem;border-radius:10px;border:1px solid #2a3a5e;background:#0e1729;color:var(--fg);font:inherit}
button{padding:.7rem 1.1rem;border:0;border-radius:10px;background:var(--accent);color:#06121f;font-weight:600;cursor:pointer}
footer{border-top:1px solid #1e293b;color:var(--muted);font-size:.9rem}
@media (max-width:640px){header,main,footer{padding:1rem}}
"""

_JS = """// Progressive enhancement only — the site works without JavaScript.
document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('a[href^="#"]').forEach((link) => {
    link.addEventListener('click', (event) => {
      const target = document.querySelector(link.getAttribute('href'));
      if (target) {
        event.preventDefault();
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        target.setAttribute('tabindex', '-1');
        target.focus({ preventScroll: true });
      }
    });
  });
});
"""


def _looks_like_heading(line: str) -> bool:
    if len(line) > 70:
        return False
    return bool(re.match(r"^[A-Z0-9][\w \-:]{2,}$", line)) and not line.endswith(".")


def _shorten(text: str, limit: int) -> str:
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def _esc(text: Any) -> str:
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


__all__ = ["draft_sections", "draft_slides", "build_static_site", "extract_points", "keywords"]
