"""AI Docs tool: generate professional documents (Markdown, TXT, DOCX, PDF)."""

from __future__ import annotations

import datetime as dt
import io
import json
import re
from typing import Any

from backend.app.core.errors import ToolError
from models.adapters import ChatMessage
from tools.base import BaseTool, Permission, ToolContext, ToolResult, ValidationReport
from tools.registry import register


@register
class DocsTool(BaseTool):
    name = "docs"
    description = "Create professional documents from a brief or explicit outline. Supports Markdown, TXT, DOCX and PDF output."
    category = "documents"
    permissions = [Permission.READ, Permission.WRITE, Permission.FILES, Permission.MODEL]
    cost_estimate = "model-tokens"
    input_schema = {
        "type": "object",
        "properties": {
            "title": {"type": "string"},
            "prompt": {"type": "string", "description": "Brief used to draft the document when no outline is given"},
            "format": {"type": "string", "enum": ["md", "txt", "docx", "pdf"], "default": "md"},
            "author": {"type": "string"},
            "subtitle": {"type": "string"},
            "sections": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "heading": {"type": "string"},
                        "body": {"type": "string"},
                        "bullets": {"type": "array", "items": {"type": "string"}},
                    },
                },
            },
            "model": {"type": "string"},
        },
        "required": ["title"],
    }
    output_schema = {
        "type": "object",
        "properties": {
            "title": {"type": "string"},
            "format": {"type": "string"},
            "markdown": {"type": "string"},
            "artifacts": {"type": "array"},
        },
    }

    def availability(self, ctx: ToolContext | None = None) -> str:
        return "AVAILABLE"

    def execute(self, ctx: ToolContext, payload: dict[str, Any]) -> ToolResult:
        title = str(self.require(payload, "title")).strip()
        if not title:
            raise ToolError("Title must not be empty")
        fmt = str(payload.get("format", "md")).lower()
        if fmt not in ("md", "txt", "docx", "pdf"):
            raise ToolError(f"Unsupported format '{fmt}'")

        sections = payload.get("sections") or []
        synthesis = "explicit"
        note = ""
        if not sections and payload.get("prompt"):
            sections, synthesis, note = self._draft_outline(payload, ctx)
        if not sections:
            sections = [{"heading": "Overview", "body": payload.get("prompt", "This document was generated by LocalAI Workspace."), "bullets": []}]

        doc = {
            "title": title,
            "subtitle": payload.get("subtitle", ""),
            "author": payload.get("author", ""),
            "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
            "synthesis": synthesis,
            "synthesis_note": note,
            "sections": sections,
        }
        markdown = render_markdown(doc)

        artifacts: list[dict[str, Any]] = []
        stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d-%H%M%S")
        base = re.sub(r"[^A-Za-z0-9._-]+", "-", title).strip("-").lower() or "document"

        if fmt == "md":
            artifacts.append(ctx.save_artifact(f"{base}-{stamp}.md", markdown, "document", "text/markdown", "documents", {"title": title}))
        elif fmt == "txt":
            artifacts.append(ctx.save_artifact(f"{base}-{stamp}.txt", _to_text(doc), "document", "text/plain", "documents", {"title": title}))
        elif fmt == "docx":
            data = _to_docx(doc)
            artifacts.append(ctx.save_artifact(f"{base}-{stamp}.docx", data, "document", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "documents", {"title": title}))
        elif fmt == "pdf":
            data = _to_pdf(doc)
            artifacts.append(ctx.save_artifact(f"{base}-{stamp}.pdf", data, "document", "application/pdf", "documents", {"title": title}))

        # Always keep the markdown source for previewing/continued editing.
        artifacts.append(ctx.save_artifact(f"{base}-{stamp}.md", markdown, "document", "text/markdown", "documents", {"title": title, "role": "source"}))

        return ToolResult(
            status="SUCCESS",
            summary=f"Document '{title}' generated as {fmt.upper()} ({len(sections)} sections).",
            data={"title": title, "format": fmt, "markdown": markdown, "sections": sections, "doc": doc, "synthesis": synthesis, "synthesis_note": note},
            artifacts=artifacts,
        )

    # ------------------------------------------------------------- drafting
    def _draft_outline(self, payload: dict[str, Any], ctx: ToolContext) -> tuple[list[dict[str, Any]], str, str]:
        """Try the LLM first; fall back to a deterministic composer (labelled)."""
        registry = getattr(ctx, "model_registry", None)
        if registry is None:
            from models.registry import registry as global_registry

            registry = global_registry

        if _chat_usable(registry):
            prompt = (
                "Write a professional document outline as JSON. Return ONLY a JSON array where each item is "
                '{"heading": string, "body": string (2-4 sentences), "bullets": [string, ...]}. '
                f"Title: {payload.get('title')}\nBrief: {payload.get('prompt')}"
            )
            try:
                completion = registry.complete([ChatMessage("user", prompt)], model=payload.get("model"), max_tokens=2500)
                text = completion.text.strip()
                start, end = text.find("["), text.rfind("]")
                if start != -1 and end != -1:
                    parsed = json.loads(text[start : end + 1])
                    sections = []
                    for item in parsed:
                        if isinstance(item, dict) and item.get("heading"):
                            sections.append(
                                {
                                    "heading": str(item.get("heading")),
                                    "body": str(item.get("body", "")),
                                    "bullets": [str(b) for b in (item.get("bullets") or [])],
                                }
                            )
                    if sections:
                        return sections, "llm", ""
            except Exception:  # noqa: BLE001 - deterministic fallback is intended
                pass

        from tools.composition import draft_sections

        sections = draft_sections(str(payload.get("title", "")), str(payload.get("prompt", "")))
        return sections, "deterministic", "Model output was unavailable; the outline was composed deterministically from the brief."

    def validate(self, ctx: ToolContext, result: ToolResult) -> ValidationReport:
        checks = [{"name": "status", "ok": result.status in ("SUCCESS", "UNAVAILABLE"), "detail": result.status}]
        if result.status == "SUCCESS":
            import os
            import zipfile

            checks.append({"name": "has_artifacts", "ok": len(result.artifacts) >= 1, "detail": f"{len(result.artifacts)}"})
            for art in result.artifacts:
                path = art.get("storage_path", "")
                exists = os.path.exists(path) and os.path.getsize(path) > 0
                checks.append({"name": f"file:{art['name']}", "ok": exists, "detail": f"{art.get('size', 0)} bytes"})
                if path.endswith(".docx") and exists:
                    ok = zipfile.is_zipfile(path)
                    checks.append({"name": "docx_is_zip", "ok": ok, "detail": "OOXML container"})
                if path.endswith(".pdf") and exists:
                    with open(path, "rb") as fh:
                        head = fh.read(5)
                    checks.append({"name": "pdf_header", "ok": head.startswith(b"%PDF"), "detail": head.decode("latin-1", "ignore")})
        return ValidationReport(valid=all(c["ok"] for c in checks), message="docs validation")


# --------------------------------------------------------------------------- #
# Renderers
# --------------------------------------------------------------------------- #
def render_markdown(doc: dict[str, Any]) -> str:
    lines = [f"# {doc['title']}"]
    if doc.get("subtitle"):
        lines.append(f"_{doc['subtitle']}_")
    meta = []
    if doc.get("author"):
        meta.append(f"**Author:** {doc['author']}")
    if doc.get("generated_at"):
        meta.append(f"**Generated:** {doc['generated_at']}")
    if meta:
        lines.append("  \n".join(meta))
    if doc.get("synthesis") == "deterministic":
        lines.append("")
        lines.append("> **Note:** composed deterministically from the brief because no language model was available. No external facts were added.")
    lines.append("")
    for section in doc.get("sections", []):
        lines.append(f"## {section.get('heading', '')}")
        lines.append("")
        if section.get("body"):
            lines.append(str(section["body"]))
            lines.append("")
        for bullet in section.get("bullets") or []:
            lines.append(f"- {bullet}")
        if section.get("bullets"):
            lines.append("")
    lines.append("---")
    lines.append("_Generated by LocalAI Workspace_")
    return "\n".join(lines)


def _to_text(doc: dict[str, Any]) -> str:
    md = render_markdown(doc)
    md = re.sub(r"^#+\s*", "", md, flags=re.M)
    return md.replace("**", "").replace("_", "")


def _to_docx(doc: dict[str, Any]) -> bytes:
    from docx import Document
    from docx.shared import Pt

    document = Document()
    document.add_heading(doc["title"], level=0)
    if doc.get("subtitle"):
        p = document.add_paragraph(doc["subtitle"])
        p.runs[0].italic = True
    if doc.get("author") or doc.get("generated_at"):
        info = document.add_paragraph()
        run = info.add_run(f"Author: {doc.get('author', '-')} | Generated: {doc.get('generated_at', '')}")
        run.font.size = Pt(9)
    for section in doc.get("sections", []):
        document.add_heading(section.get("heading", ""), level=1)
        if section.get("body"):
            document.add_paragraph(str(section["body"]))
        for bullet in section.get("bullets") or []:
            document.add_paragraph(str(bullet), style="List Bullet")
    document.add_paragraph("Generated by LocalAI Workspace")
    buf = io.BytesIO()
    document.save(buf)
    return buf.getvalue()


def _to_pdf(doc: dict[str, Any]) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer

    buf = io.BytesIO()
    styles = getSampleStyleSheet()
    story: list[Any] = [Paragraph(_esc(doc["title"]), styles["Title"]), Spacer(1, 0.4 * cm)]
    if doc.get("subtitle"):
        story.append(Paragraph(_esc(doc["subtitle"]), styles["Italic"]))
    story.append(Paragraph(f"Generated by LocalAI Workspace — {_esc(doc.get('generated_at', ''))}", styles["Normal"]))
    story.append(Spacer(1, 0.6 * cm))
    for section in doc.get("sections", []):
        story.append(Paragraph(_esc(section.get("heading", "")), styles["Heading2"]))
        if section.get("body"):
            story.append(Paragraph(_esc(section["body"]), styles["BodyText"]))
        bullets = section.get("bullets") or []
        if bullets:
            story.append(
                ListFlowable([ListItem(Paragraph(_esc(b), styles["BodyText"])) for b in bullets], bulletType="bullet", start="•")
            )
        story.append(Spacer(1, 0.3 * cm))
    SimpleDocTemplate(buf, pagesize=A4, leftMargin=2 * cm, rightMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm).build(story)
    return buf.getvalue()


def _esc(text: Any) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _chat_usable(registry: Any) -> bool:
    if registry is None:
        return False
    checker = getattr(registry, "chat_available", None)
    if callable(checker):
        try:
            return bool(checker())
        except Exception:  # noqa: BLE001
            return False
    try:
        return bool(registry.chat_models())
    except Exception:  # noqa: BLE001
        return False


__all__ = ["DocsTool", "render_markdown"]
